# COMP5329 - Deep Learning

**Tutorial 1 - Introduction**

**Semester 1, 2026**

## 1. Environment Setup

### 1.1 Install Anaconda

**Anaconda** is a Python distribution that bundles `conda` — a package and environment manager — with hundreds of pre-installed data science libraries. It is the recommended way to set up an isolated, reproducible Python environment for deep learning, avoiding dependency conflicts between projects.

**Installation steps:**
1. Download the installer for your OS from https://www.anaconda.com/download and run it (accept default options).
2. Open a **new terminal** (or Anaconda Prompt on Windows) and verify:
    ```
    conda --version
    ```
3. Create a dedicated environment for this course:
    ```
    conda create -n deepl python=3.10
    conda activate deepl
    ```
   Always activate this environment before working on course materials.

---

### 1.2 Install PyTorch

**PyTorch** is the primary deep learning framework used throughout this course. It provides GPU-accelerated tensor computation and automatic differentiation (autograd), which powers all neural network training.

**Installation steps:**
1. With your `deepl` environment active, visit https://pytorch.org/get-started/locally/
2. Select your **OS**, package manager (`conda`), and **CUDA version** (choose *CPU-only* if you have no NVIDIA GPU).
3. Run the generated `conda install` command. For example:
    ```
    # CPU-only (suitable for most laptops)
    conda install pytorch torchvision torchaudio cpuonly -c pytorch
    ```
    ```
    # CUDA 12.1 (for machines with an NVIDIA GPU)
    conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
    ```

**Verify the installation:**

In [ ]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available: ", torch.cuda.is_available())
# If CUDA is available, prints the GPU name:
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

## 2. IDE Setup — Visual Studio Code

**Visual Studio Code (VSCode)** is a lightweight, extensible code editor with excellent support for Python, Jupyter notebooks, and AI-assisted development. It is the recommended IDE for this course.

### 2.1 Installation
1. Download from https://code.visualstudio.com/ and run the installer.
2. Open VSCode, go to the **Extensions** panel (`Ctrl+Shift+X` / `Cmd+Shift+X`), and install:
   - **Python** (Microsoft) — language support, linting, debugging.
   - **Jupyter** — run `.ipynb` notebooks directly inside VSCode.

### 2.2 Connect to your Conda Environment
1. Open the Command Palette (`Ctrl+Shift+P` / `Cmd+Shift+P`).
2. Type **`Python: Select Interpreter`** and choose the `deepl` conda environment.
3. When opening a notebook, click the **kernel selector** (top-right) and select the same environment.

### 2.3 Useful Shortcuts

| Action | Windows/Linux | macOS |
|--------|--------------|-------|
| Open terminal | Ctrl + \` | Cmd + \` |
| Run notebook cell | Shift + Enter | Shift + Enter |
| Command palette | Ctrl + Shift + P | Cmd + Shift + P |
| Quick file open | Ctrl + P | Cmd + P |
| Toggle sidebar | Ctrl + B | Cmd + B |

## 3. PyTorch Tensor Operations

**Tensors** are the fundamental data structure in PyTorch — multi-dimensional arrays analogous to NumPy arrays, but with two critical additions: **GPU acceleration** and **automatic differentiation** (needed for backpropagation). In deep learning, all inputs, weights, gradients, and intermediate activations are represented as tensors.

The examples below show PyTorch and NumPy side-by-side, so you can see the correspondence between the two APIs and understand when to use each.

**Create a 5×5 integer matrix** with random values in $[0, 5)$:

In [ ]:
# by pytorch
import torch

# torch.randint(lower_bound, upper_bound, (rows, columns))
A = torch.randint(0, 5, (5, 5))

print(A)

tensor([[3, 3, 0, 4, 2],
        [0, 1, 1, 2, 2],
        [4, 2, 3, 0, 1],
        [1, 4, 0, 2, 2],
        [0, 2, 1, 3, 3]])


In [2]:
# by numpy
import numpy as np

# numpy.random.randint(lower_bound, upper_bound, (rows, columns))
A_np = np.random.randint(0, 5, (5, 5))

print(A_np)

[[3 4 1 2 4]
 [4 3 1 0 0]
 [3 3 3 4 4]
 [4 2 4 2 3]
 [4 1 4 0 3]]


In [3]:
A[3][2]

tensor(0)

### 3.1 Basic Tensor Operations

For matrices $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{m \times n}$, the following operations are commonly used in deep learning (e.g., in computing weighted sums, loss functions, and gradient updates):

| Operation | Math notation | PyTorch | NumPy |
|-----------|--------------|---------|-------|
| Addition | $C = A + B$ | `A + B` | `A + B` |
| Subtraction | $C = A - B$ | `A - B` | `A - B` |
| Element-wise product | $C_{ij} = A_{ij} \cdot B_{ij}$ | `A * B` | `A * B` |
| Matrix product | $C = A B^T$ | `torch.matmul(A, B.T)` or `A @ B.T` | `np.matmul(A, B.T)` |

Define $A \in \mathbb{R}^{5 \times 6}$, $B \in \mathbb{R}^{5 \times 6}$:

In [5]:
A = torch.randint(0, 5, (5, 6))
print(A)

B = torch.randint(0, 5, (5, 6))
print(B)

tensor([[3, 0, 4, 0, 2, 3],
        [4, 1, 3, 1, 3, 4],
        [3, 4, 0, 4, 1, 3],
        [3, 1, 0, 3, 0, 0],
        [4, 0, 0, 2, 4, 3]])
tensor([[2, 1, 2, 4, 2, 2],
        [1, 3, 2, 3, 3, 1],
        [4, 1, 1, 4, 4, 2],
        [3, 1, 2, 1, 1, 2],
        [3, 3, 4, 3, 2, 4]])


In [6]:
A_np = np.random.randint(0, 5, (5, 6))
print(A_np)

B_np = np.random.randint(0, 5, (5, 6))
print(B_np)

[[3 3 3 2 4 3]
 [3 3 3 2 2 4]
 [3 3 1 2 0 2]
 [2 0 0 1 4 1]
 [2 0 0 4 3 3]]
[[2 3 0 0 3 4]
 [4 1 3 1 1 0]
 [0 2 4 0 1 4]
 [1 0 3 4 3 1]
 [4 1 3 2 2 2]]


* **Add**: $C = A + B$
* **Substract**: $C = A - B$

In [11]:
# implement A + B in torch
C = A + B
print(C)

# implement A + B in numpy
C_np = A_np + B_np
print(C_np)

# implement A - B in torch
C = A - B
print(C)

# implement A - B in numpy
C_np = A_np - B_np
print(C_np)

tensor([[5, 1, 6, 4, 4, 5],
        [5, 4, 5, 4, 6, 5],
        [7, 5, 1, 8, 5, 5],
        [6, 2, 2, 4, 1, 2],
        [7, 3, 4, 5, 6, 7]])
[[5 6 3 2 7 7]
 [7 4 6 3 3 4]
 [3 5 5 2 1 6]
 [3 0 3 5 7 2]
 [6 1 3 6 5 5]]
tensor([[ 1, -1,  2, -4,  0,  1],
        [ 3, -2,  1, -2,  0,  3],
        [-1,  3, -1,  0, -3,  1],
        [ 0,  0, -2,  2, -1, -2],
        [ 1, -3, -4, -1,  2, -1]])
[[ 1  0  3  2  1 -1]
 [-1  2  0  1  1  4]
 [ 3  1 -3  2 -1 -2]
 [ 1  0 -3 -3  1  0]
 [-2 -1 -3  2  1  1]]


* **Element-wise Multiplication** $C = A \odot B \in \mathbf{R}^{m \times n}, \forall i,j$, which means $C_{i, j} = A_{i, j} * B_{i, j}$.

In [12]:
# implement A * B in torch
C = A * B
print(C)

# implement A * B in numpy
C_np = A_np * B_np
print(C_np)


tensor([[ 6,  0,  8,  0,  4,  6],
        [ 4,  3,  6,  3,  9,  4],
        [12,  4,  0, 16,  4,  6],
        [ 9,  1,  0,  3,  0,  0],
        [12,  0,  0,  6,  8, 12]])
[[ 6  9  0  0 12 12]
 [12  3  9  2  2  0]
 [ 0  6  4  0  0  8]
 [ 2  0  0  4 12  1]
 [ 8  0  0  8  6  6]]


* **Multiplication** $C = A \times B^T$, which means $C_{i,j} = ∑_{l=1}^{n}A_{i,l} * B_{l, j}$

* $A_{m\times n}, B_{n \times k}$ so we have output $C_{m \times k}$

In [14]:
# implement A * B in torch
C = torch.matmul(A, B.T)
print(C)

# implement A * B in numpy
C_np = np.matmul(A_np, np.transpose(B_np))
print(C_np)


tensor([[24, 20, 30, 25, 41],
        [33, 29, 44, 31, 52],
        [34, 33, 42, 24, 47],
        [19, 15, 25, 13, 21],
        [30, 25, 46, 24, 38]])
[[39 30 34 35 42]
 [37 28 36 30 40]
 [23 20 18 16 26]
 [20 13  8 19 20]
 [25 15 15 30 28]]
tensor([[24, 20, 30, 25, 41],
        [33, 29, 44, 31, 52],
        [34, 33, 42, 24, 47],
        [19, 15, 25, 13, 21],
        [30, 25, 46, 24, 38]])
tensor([[24, 20, 30, 25, 41],
        [33, 29, 44, 31, 52],
        [34, 33, 42, 24, 47],
        [19, 15, 25, 13, 21],
        [30, 25, 46, 24, 38]])


In [15]:
# some other ways to implement A * B in torch
C = A @ B.T
print(C)

C = A.mm(B.T)
print(C)

tensor([[24, 20, 30, 25, 41],
        [33, 29, 44, 31, 52],
        [34, 33, 42, 24, 47],
        [19, 15, 25, 13, 21],
        [30, 25, 46, 24, 38]])
tensor([[24, 20, 30, 25, 41],
        [33, 29, 44, 31, 52],
        [34, 33, 42, 24, 47],
        [19, 15, 25, 13, 21],
        [30, 25, 46, 24, 38]])


## 5. AI Assistant — Claude Code

### 5.1 Introduction

**Claude Code** is Anthropic's official AI-powered coding assistant that runs directly in your terminal or IDE. Unlike browser-based chatbots, Claude Code has **direct access to your local files** — it can read, write, edit, and reason about your entire project without you copying and pasting anything.

**Why is this relevant for a deep learning course?**

| Task | How Claude Code helps |
|------|-----------------------|
| Understanding unfamiliar PyTorch APIs | Ask in plain English; Claude reads your actual code to answer |
| Debugging shape mismatches and errors | Paste the traceback; Claude diagnoses the root cause in context |
| Writing boilerplate | Generate Dataset classes, training loops, and evaluation scripts instantly |
| Explaining paper implementations | Ask what a specific code block does mathematically |

---

> ### CRITICAL: Always Review AI-Generated Code
>
> **Treating Claude Code output as correct without review is dangerous.** AI assistants can produce code that looks convincing but contains subtle bugs, incorrect assumptions, or logic errors — especially in deep learning, where mistakes in loss functions, gradient flow, or data preprocessing are often silent (no crash, but wrong results).
>
> **Specific risks in this course:**
> - **Incorrect tensor shapes** — generated code may silently broadcast where it should fail.
> - **Wrong loss or metric** — a plausible-looking function may compute the wrong quantity for your task.
> - **Training loop errors** — missing `.zero_grad()`, double-counting samples, or incorrect averaging can corrupt training silently.
> - **Data leakage** — normalisation or augmentation applied before splitting can leak test information into training.
>
> **The right mindset:** Use Claude Code as a fast first draft, not a final answer. You are responsible for understanding and verifying every line of code that runs in your experiments.
>
> - Read the generated code line by line before running it.
> - Test on small inputs with known expected outputs.
> - Cross-check against lecture slides, documentation, or reference implementations.
> - If you cannot explain what a generated line does, do not accept it.

### 5.2 Setup

Claude Code can be installed in two ways: as a **terminal CLI** (full command-line access) or as a **VSCode / Cursor extension** (IDE-embedded chat and editing).

---

#### Installation — Terminal (CLI)

**Prerequisite:** Node.js 18 or later — download from https://nodejs.org/

**macOS / Linux / WSL:**
```
curl -fsSL https://claude.ai/install.sh | bash
```

**Windows (PowerShell):**
```
irm https://claude.ai/install.ps1 | iex
```

Verify the installation and start a session:
```
claude --version
cd /path/to/your/project
claude
```

---

#### Installation — VSCode / Cursor Extension

1. Open the **Extensions** panel (`Ctrl+Shift+X` / `Cmd+Shift+X`).
2. Search for **Claude Code** and install it.
3. Reload the editor — Claude Code appears in the Activity Bar.
4. Alternatively: Command Palette → **Claude Code: Open**.

This provides the same file-editing and chat capabilities without leaving the IDE.

---

#### Authentication

Claude Code supports three authentication methods:

| Method | When to use |
|--------|-------------|
| **Claude.ai subscription** (Pro or Max) | You have a paid Claude.ai account — log in with your existing credentials. Simplest option for individuals. |
| **Anthropic API key** | You have a usage-based account on [console.anthropic.com](https://console.anthropic.com). Suitable for research or programmatic access. |
| **Cloud provider** (Amazon Bedrock, Google Vertex AI) | Your organisation routes AI traffic through AWS or Google Cloud for compliance or billing reasons. Requires cloud credentials instead of an Anthropic account. |

Run `claude` the first time and follow the interactive prompts to select and configure your method.

---

#### Permission Modes

Claude Code has three modes that control how much autonomy it has over your files:

| Mode | What it does | When to use |
|------|-------------|-------------|
| **Auto** | Applies all file edits automatically without asking for approval each time | Rapid prototyping — you trust Claude to modify files freely within the session |
| **Ask before edits** *(default)* | Prompts you before each file edit or write operation | Normal development — you want to review every proposed change before it is applied |
| **Plan** | Claude analyses your codebase and proposes a plan but **cannot modify any files** | Understanding a problem or reviewing an approach before committing to changes |

> **Note — file creation and shell commands:** These modes govern edits to *existing* files. Regardless of mode, Claude Code will still prompt for confirmation before **creating new files or executing shell commands** (which could delete or overwrite files). To bypass all permission checks — for example, in an automated pipeline or a sandboxed container — start Claude Code with:
> ```
> claude --dangerously-skip-permissions
> ```
> Only use this flag in isolated environments (e.g. a Docker container or VM) where unintended changes cannot cause lasting harm.

In [ ]:
# Run the following commands in your TERMINAL (not here in the notebook).
#
# Install Claude Code (macOS/Linux/WSL):
#   curl -fsSL https://claude.ai/install.sh | bash
#
# Install Claude Code (Windows PowerShell):
#   irm https://claude.ai/install.ps1 | iex
#
# Verify installation:
#   claude --version
#
# Start an interactive session in your project directory:
#   cd /path/to/your/project
#   claude

### 5.3 Overview and Basic Operations

Once installed, Claude Code operates through a conversational interface. It reads your working directory and can take actions (edit files, run commands) with your approval.

#### Terminal usage

| Goal | Command |
|------|---------|
| Start an interactive session | `claude` |
| Ask a one-off question | `claude "What does the backward() call do in PyTorch?"` |
| Debug a file | `claude "Find and fix the bug in train.py"` |
| Generate code | `claude "Add a learning rate scheduler to the training loop in train.py"` |
| Explain code | `claude "Explain what the forward() method in model.py does step by step"` |

#### In-IDE usage (VSCode)
- **Select any block of code** → right-click → **Ask Claude** to get an inline explanation.
- Use the **integrated chat panel** to ask questions scoped to the open file.
- Claude can **directly edit the open file** when you instruct it to (e.g. "refactor this class").

#### Example workflow for this course
```
$ claude "My CNN is overfitting on MNIST. Add dropout after each conv layer in model.py."
```
Claude will read `model.py`, propose the changes, show you a diff, and apply them upon your confirmation.

---

**Remember:** The diff Claude shows you is your opportunity to review — do not click "accept" automatically. Read the proposed changes, verify the logic, and only confirm when you understand what is being modified and why.